# Generated by Django 3.0.6 on 2020-05-20 14:55

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('monzo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='TaggedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monzo.Transaction')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monzo_taggedtransaction_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='monzo.TaggedTransaction', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
