# Generated by Django 3.0.6 on 2020-05-21 10:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('monzo', '0004_auto_20200521_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='user_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='monzo.TaggedMerchant', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
