# Generated by Django 3.0.6 on 2020-05-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monzo', '0005_auto_20200521_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
