# Generated by Django 3.0.6 on 2020-05-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monzo', '0006_auto_20200521_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
