# Generated by Django 3.0.6 on 2020-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monzo', '0007_transaction_user_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=10)),
                ('sort_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('service_user_number', models.CharField(max_length=10)),
            ],
        ),
    ]
