# Generated by Django 3.0.6 on 2020-05-23 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monzo', '0008_counterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monzo.CounterParty'),
        ),
    ]
