# Generated by Django 3.0.6 on 2020-05-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monzo', '0009_transaction_counterparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
